services:
  web:
    build: .
    container_name: todo_app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: mylist.settings
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn mylist.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60
      "
    volumes:
      - static_data:/app/staticfiles
volumes:
  static_data: